#!/bin/sh

set -e

syslog -s -l warn "Set environment variables with /etc/environment $(whoami) - start"

launchctl setenv HOUDINI_VERBOSE_ERROR		1
launchctl setenv HOUDINI_DSO_ERROR		    3
launchctl setenv FN_UPDATE_OVERRIDE_FPS		30
launchctl setenv NUKE_USE_FIXED_UPDATE		1
launchctl setenv FN_DISABLE_LICENSE_DIALOG	TRUE
launchctl setenv IH_SHOW_CODE			    romeo
launchctl setenv IH_SHOW_ROOT			    /Volumes/romeo_primary/SHOTS
launchctl setenv IH_SHOW_CFG_PATH		    /Volumes/romeo_primary/SHOTS/SHARED/romeo/lib/romeo.cfg
launchctl setenv IH_SHOW_CFG_LUT		    /Volumes/romeo_primary/SHOTS/SHARED/lut/RomeoCV_Rec709.cube
launchctl setenv PYTHONPATH			        /Volumes/romeo_primary/SHOTS/SHARED/lib/python:/Volumes/romeo_primary/SHOTS/SHARED/shotgun/install/core/python:/Volumes/romeo_primary/SHOTS/SHARED/lib/nuke/pipeline
launchctl setenv NUKE_INTERACTIVE		    1
launchctl setenv OCIO				       /Volumes/romeo_primary/SHOTS/SHARED/lib/ocio_configs/nuke-default/config.ocio
if [ -x /usr/libexec/path_helper ]; then
    export PATH=""
    eval `/usr/libexec/path_helper -s`
    launchctl setenv PATH $PATH
fi

osascript -e 'tell app "Dock" to quit'

syslog -s -l warn "Set environment variables with /etc/environment $(whoami) - complete"

