#!/bin/bash

export HOUDINI_VERBOSE_ERROR=1
export HOUDINI_DSO_ERROR=3
export FN_UPDATE_OVERRIDE_FPS=30
export NUKE_USE_FIXED_UPDATE=1
export FN_DISABLE_LICENSE_DIALOG=TRUE
export IH_SHOW_CODE=romeo
export IH_SHOW_ROOT=/Volumes/romeo_inhouse/romeo
export IH_SHOW_CFG_PATH=/Volumes/romeo_inhouse/romeo/SHARED/romeo/lib/romeo.cfg
export IH_SHOW_CFG_LUT=/Volumes/romeo_inhouse/romeo/SHARED/lut/RomeoCV_Rec709.cube
export PYTHONPATH=/Volumes/romeo_inhouse/romeo/SHARED/lib/python:/Volumes/romeo_inhouse/romeo/SHARED/shotgun/install/core/python:/Volumes/romeo_inhouse/romeo/SHARED/lib/nuke/pipeline
export NUKE_INTERACTIVE=1
export OCIO=/Volumes/romeo_inhouse/romeo/SHARED/lib/ocio_configs/nuke-default/config.ocio
