#!/bin/bash

export HOUDINI_VERBOSE_ERROR=1
export HOUDINI_DSO_ERROR=3
export FN_UPDATE_OVERRIDE_FPS=30
export NUKE_USE_FIXED_UPDATE=1
export FN_DISABLE_LICENSE_DIALOG=TRUE
export IH_SHOW_CODE=morbius
export IH_SHOW_ROOT=/Volumes/qppe_das01/morbius
export IH_SHOW_CFG_PATH=/Volumes/qppe_das01/morbius/SHARED/lib/morbius.cfg
export IH_SHOW_CFG_LUT=/Volumes/qppe_das01/morbius/SHARED/lut/MorbiusCV_Rec709.cube
export PYTHONPATH=/Volumes/qppe_das01/SHARED/lib/python:/Volumes/qppe_das01/SHARED/lib/nuke/pipeline
export NUKE_INTERACTIVE=1
export OCIO=/Volumes/qppe_das01/morbius/SHARED/lib/ocio_configs/nuke-default/config.ocio
